#!/usr/bin/env python3
"""Diff two JSON inventories generated by ae_sdk_inventory.py."""
from __future__ import annotations
import argparse, json
from pathlib import Path


def load(p):
    d=json.loads(Path(p).read_text("utf-8"))
    return {t["name"]:{f["name"]:f["signature"] for f in t["functions"]} for t in d["tables"]}

def main():
    ap=argparse.ArgumentParser()
    ap.add_argument("old")
    ap.add_argument("new")
    ap.add_argument("--markdown", default="sdk-diff.md")
    args=ap.parse_args()
    a=load(args.old); b=load(args.new)
    lines=["# After Effects SDK contract diff",""]
    old_s,new_s=set(a),set(b)
    lines += ["## Contract tables",""]
    lines += [f"- Added: {', '.join(f'`{x}`' for x in sorted(new_s-old_s)) or 'none'}"]
    lines += [f"- Removed: {', '.join(f'`{x}`' for x in sorted(old_s-new_s)) or 'none'}",""]
    changes=0
    for s in sorted(old_s & new_s):
        oa,nb=a[s],b[s]
        added=set(nb)-set(oa); removed=set(oa)-set(nb)
        changed={f for f in set(oa)&set(nb) if oa[f]!=nb[f]}
        if not (added or removed or changed): continue
        changes+=1
        lines += [f"## `{s}`",""]
        if added: lines.append("Added: "+", ".join(f"`{x}`" for x in sorted(added)))
        if removed: lines.append("Removed: "+", ".join(f"`{x}`" for x in sorted(removed)))
        if changed:
            lines += ["Changed signatures:",""]
            for f in sorted(changed):
                lines += [f"- `{f}`",f"  - old: `{oa[f]}`",f"  - new: `{nb[f]}`"]
        lines.append("")
    if changes==0:
        lines += ["No signature-level changes detected in shared contract tables.",""]
    Path(args.markdown).write_text("\n".join(lines),"utf-8")
    print(args.markdown)
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
