#!/usr/bin/env python3
"""Stage documentation, regenerate MASTER and SHA-256 manifest reproducibly."""
import argparse
import hashlib
from pathlib import Path
import re
import shutil
import subprocess

ROOT = Path(__file__).resolve().parents[1]
MASTER = "MASTER-AE-DEVELOPER-BIBLE.md"
GENERATED = {MASTER, "MANIFEST.sha256"}


def tracked_files():
    output = subprocess.check_output(["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"], cwd=ROOT)
    return sorted({Path(p.decode()) for p in output.split(b"\0") if p and (ROOT / p.decode()).is_file()})


def source_digest(files):
    """Content identity, not Git revision; independent of checkout path and outputs."""
    digest = hashlib.sha256()
    for path in sorted(p for p in files if p.as_posix() not in GENERATED):
        data = (ROOT / path).read_bytes()  # Missing source must fail, never hash as empty.
        digest.update(path.as_posix().encode("utf-8") + b"\0")
        digest.update(hashlib.sha256(data).digest())
    return digest.hexdigest()


def generated(files):
    documents = [p for p in files if p.suffix == ".md" and p.name != MASTER]
    documents.sort(key=lambda p: (str(p) != "README.md", str(p)))
    digest = source_digest(files)
    sections = [
        "---\n"
        "search:\n"
        "  exclude: true\n"
        "---\n\n"
        "# AE Developer Bible — MASTER v1.1\n\n"
        "Generated by `python3 scripts/build_docs.py`. "
        "Source chapters are authoritative.\n"
        f"\nSource content SHA-256: `{digest}`. This is a content digest, not a Git SHA.\n"
    ]
    for path in documents:
        text = (ROOT / path).read_text()
        def rewrite(match):
            target = match[1]
            if ":" in target or target.startswith(("#", "/")):
                return match[0]
            return "](" + (path.parent / target).as_posix() + ")"
        text = re.sub(r"\]\(([^\s)]+)\)", rewrite, text)
        sections.append(f"\n---\n\n<!-- SOURCE: {path.as_posix()} -->\n\n{text.rstrip()}\n")
    master = "\n".join(sections)
    hashes = []
    for path in sorted(set(files) | {Path(MASTER)}):
        if str(path) == "MANIFEST.sha256":
            continue
        data = master.encode() if str(path) == MASTER else (ROOT / path).read_bytes()
        hashes.append(f"{hashlib.sha256(data).hexdigest()}  {path.as_posix()}")
    return {MASTER: master, "MANIFEST.sha256": "\n".join(hashes) + "\n"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--output-root", type=Path, help="Generate/stage outside the source checkout")
    args = parser.parse_args()
    output_root = args.output_root.resolve() if args.output_root else ROOT
    if not args.check:
        output_root.mkdir(parents=True, exist_ok=True)
    files = tracked_files()
    stale = []
    for name, content in generated(files).items():
        path = output_root / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.write_text(content)
    if args.check:
        if stale:
            print("Stale generated files: " + ", ".join(stale))
        return bool(stale)
    stage = output_root / "docs"
    if stage.exists():
        shutil.rmtree(stage)
    stage.mkdir()
    for path in sorted(set(files) | {Path(p) for p in GENERATED}):
        if path.suffix not in (".md", ".cpp", ".h", ".jsx", ".js", ".py", ".sh", ".ps1", ".json"):
            continue
        destination = stage / path
        destination.parent.mkdir(parents=True, exist_ok=True)
        source = output_root / path if path.as_posix() in GENERATED else ROOT / path
        shutil.copyfile(source, destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
